using Unity.AI.Navigation;
using UnityEngine;

/// <summary>
/// Manages the navigation state of a procedural road segment.
/// Attach this to the main road GameObject generated by RoadNetworkGenerator.
/// </summary>
public class RoadNavigationControl : MonoBehaviour
{
    [Tooltip("The NavMeshModifier responsible for carving a hole in the NavMesh.")]
    [SerializeField]
    private NavMeshModifier navModifier;

    private bool isBlocked = false;

    /// <summary>
    /// Initializes the component with the required NavMeshModifier.
    /// </summary>
    /// <param name="modifierToControl">The modifier to enable/disable.</param>
    public void Initialize(NavMeshModifier modifierToControl)
    {
        navModifier = modifierToControl;
        // Ensure the road is navigable by default when generated.
        SetNavigationBlocked(false);
    }

    /// <summary>
    /// Enables or disables navigation on this road segment.
    /// </summary>
    /// <param name="isBlocked">True to block navigation (carve), false to allow it.</param>
    public void SetNavigationBlocked(bool shouldBlock)
    {
        if (navModifier == null)
        {
            Debug.LogWarning("NavMeshModifier is not assigned on this road segment.", this);
            return;
        }

        // Enable the modifier to carve a hole, disabling it to allow navigation.
        navModifier.enabled = shouldBlock;
        isBlocked = shouldBlock;
        
        Debug.Log($"Road segment '{gameObject.name}' navigation blocked: {isBlocked}");
    }

    /// <summary>
    /// Toggles the current navigation state of the road.
    /// </summary>
    public void ToggleNavigationBlock()
    {
        SetNavigationBlocked(!isBlocked);
    }
}